import type { Screenshot, Thread } from "./types";

/** First-run fixtures. Real ingests join these; "Reset demo data" restores them. */

export const seedThreads: Thread[] = [
  { id: "pricing-redesign", name: "Pricing page redesign" },
  { id: "onboarding-teardown", name: "Onboarding teardown" },
  { id: "capso-bugs", name: "Capso UI bugs" },
  { id: "q3-launch", name: "Q3 launch campaign" },
].map((t) => ({
  ...t,
  createdAt: "2026-03-01T00:00:00Z",
  lastActiveAt: "2026-07-30T00:00:00Z",
  archived: false,
}));

type SeedInput = Omit<
  Screenshot,
  "status" | "assignmentSource" | "source" | "imageDataUrl" | "archived" | "suggestedThreadId"
> & { suggestedThreadId?: string | null };

const raw: SeedInput[] = [
  {
    id: "s1",
    title: "Linear — pricing, annual toggle",
    summary:
      "Three-tier pricing with an annual/monthly toggle that shows the saving inline on the toggle itself.",
    whySaved: "The savings badge sits on the toggle, not under the price — worth stealing.",
    ocrText:
      "Pricing\nFree — for individuals\nBasic $8 /user /month\nBusiness $14 /user /month\nEnterprise — contact us\nBilled annually · Save 20%\nStart free trial",
    intent: "competitor",
    type: "web_page",
    threadId: "pricing-redesign",
    confidence: 0.94,
    capturedAt: "2026-03-14T09:12:00Z",
    aspect: "wide",
    hue: 250,
  },
  {
    id: "s2",
    title: "Stripe — checkout empty state",
    summary: "Empty cart state using a single line of copy and one primary action.",
    whySaved: "Reference for our own empty states — one action, no illustration.",
    ocrText: "Nothing here yet.\nAdd your first product to get started.\nAdd product",
    intent: "design_inspiration",
    type: "ui_screen",
    threadId: "pricing-redesign",
    confidence: 0.88,
    capturedAt: "2026-03-16T14:40:00Z",
    aspect: "square",
    hue: 205,
  },
  {
    id: "s3",
    title: "Overlay chip overlaps traffic lights",
    summary:
      "The suggestion chip renders under the window controls at 1280px width on the second display.",
    whySaved: "Reproducible bug — only on the external monitor.",
    ocrText: "Project = Pricing page redesign · Type = web_page\nConfirm   Adjust   Ignore",
    intent: "ux_bug",
    type: "ui_screen",
    threadId: "capso-bugs",
    confidence: 0.91,
    capturedAt: "2026-07-28T11:02:00Z",
    aspect: "wide",
    hue: 12,
  },
  {
    id: "s4",
    title: "Notion — AI accept / discard menu",
    summary: "Three-verb AI action menu: Accept, Discard, Try again.",
    whySaved: "Exactly the vocabulary our overlay chip should use.",
    ocrText: "Accept\nDiscard\nTry again\nGet unlimited AI",
    intent: "design_inspiration",
    type: "ui_screen",
    threadId: "onboarding-teardown",
    confidence: 0.86,
    capturedAt: "2026-07-21T16:20:00Z",
    aspect: "tall",
    hue: 40,
  },
  {
    id: "s5",
    title: "Superhuman — onboarding step 3",
    summary: "Keyboard-shortcut teaching screen with a single practice action per step.",
    whySaved: "One concept per screen — the pacing we want for hotkey onboarding.",
    ocrText: "Step 3 of 6\nPress ⌘K to jump anywhere.\nTry it now.",
    intent: "reference",
    type: "ui_screen",
    threadId: "onboarding-teardown",
    confidence: 0.79,
    capturedAt: "2026-06-02T08:55:00Z",
    aspect: "wide",
    hue: 285,
  },
  {
    id: "s6",
    title: "Ad hook — 'stop losing screenshots'",
    summary: "Short-form ad with the pain stated in the first three words.",
    whySaved: "Hook structure for the launch reel.",
    ocrText: "You screenshot it.\nYou forget it.\nEvery time.",
    intent: "marketing_hook",
    type: "photo",
    threadId: "q3-launch",
    confidence: 0.83,
    capturedAt: "2026-07-09T19:31:00Z",
    aspect: "tall",
    hue: 330,
  },
  {
    id: "s7",
    title: "Raycast — command palette",
    summary: "Command palette with inline result grouping and a persistent footer of actions.",
    whySaved: "Footer action bar pattern for our search omnibox.",
    ocrText: "Search for apps and commands…\nSuggestions\nCommands\n↵ Open   ⌘K Actions",
    intent: "design_inspiration",
    type: "ui_screen",
    threadId: "pricing-redesign",
    confidence: 0.9,
    capturedAt: "2026-05-11T13:05:00Z",
    aspect: "wide",
    hue: 195,
  },
  {
    id: "s8",
    title: "Arc — sidebar project grouping",
    summary: "Sidebar splits pinned spaces from loose tabs with a hairline divider.",
    whySaved: "Model for Inbox-above-projects ordering.",
    ocrText: "Spaces\nPinned\nToday",
    intent: "reference",
    type: "ui_screen",
    threadId: "onboarding-teardown",
    confidence: 0.81,
    capturedAt: "2026-04-22T10:14:00Z",
    aspect: "tall",
    hue: 160,
  },
  {
    id: "s9",
    title: "Thumbnail stretches on retina",
    summary: "Grid thumbnail loses aspect ratio when the source capture is HiDPI.",
    whySaved: "Second display again — likely the same scale-factor bug.",
    ocrText: "captured 2026-07-29 · 3024 × 1964 · scale 2x",
    intent: "ux_bug",
    type: "ui_screen",
    threadId: "capso-bugs",
    confidence: 0.87,
    capturedAt: "2026-07-29T15:48:00Z",
    aspect: "square",
    hue: 8,
  },
  {
    id: "s10",
    title: "競品 changelog 頁面",
    summary: "Changelog with screenshots per release and a filter by product area.",
    whySaved: "Format reference if we ever ship a public changelog.",
    ocrText: "更新日誌\n2026 年 7 月 — 改進搜尋排序、加快擷取速度\n2026 年 6 月 — 新增專案分類",
    intent: "competitor",
    type: "web_page",
    threadId: "q3-launch",
    confidence: 0.74,
    capturedAt: "2026-07-18T12:26:00Z",
    aspect: "wide",
    hue: 220,
  },
  {
    id: "s11",
    title: "Untitled capture",
    summary: "A settings panel with toggles for notification frequency and quiet hours.",
    whySaved: "Unclear — no strong signal from surrounding context.",
    ocrText: "Notifications\nQuiet hours  22:00 – 08:00\nDaily digest",
    intent: "other",
    type: "ui_screen",
    threadId: null,
    suggestedThreadId: "onboarding-teardown",
    confidence: 0.41,
    capturedAt: "2026-07-30T17:03:00Z",
    aspect: "square",
    hue: 100,
  },
  {
    id: "s12",
    title: "Dashboard with revenue chart",
    summary: "Analytics dashboard showing MRR growth and churn side by side.",
    whySaved: "Possibly competitor research, possibly your own metrics.",
    ocrText: "MRR $12,480\nChurn 2.1%\nNet new 34\nLast 30 days",
    intent: "competitor",
    type: "chart",
    threadId: null,
    suggestedThreadId: "q3-launch",
    confidence: 0.63,
    capturedAt: "2026-07-30T18:22:00Z",
    aspect: "wide",
    hue: 268,
  },
  {
    id: "s13",
    title: "Mobile nav drawer",
    summary: "Slide-over navigation with large tap targets and a search field pinned to the top.",
    whySaved: "Layout reference for a future mobile read view.",
    ocrText: "Home\nLibrary\nProjects\nSettings",
    intent: "design_inspiration",
    type: "ui_screen",
    threadId: null,
    suggestedThreadId: "onboarding-teardown",
    confidence: 0.58,
    capturedAt: "2026-07-31T08:41:00Z",
    aspect: "tall",
    hue: 340,
  },
];

export const seedScreenshots: Screenshot[] = raw.map((s) => ({
  ...s,
  suggestedThreadId: s.suggestedThreadId ?? null,
  status: "done",
  assignmentSource: s.threadId ? "auto" : null,
  source: "seed",
  imageDataUrl: null,
  archived: false,
}));
