import { NextResponse } from "next/server";

/**
 * Relay between the Chrome extension and the browser-side store.
 *
 * A service worker cannot write to *the web app's* origin storage — it can write
 * to its own — so something server-side has to hold the bytes in between. That
 * remains true after the Supabase migration, which is why this exists at all.
 *
 * **This relay is not durable and does not need to be.** It is a module-scope
 * array: on serverless it is per-instance and evaporates on recycle. The
 * durability lives in the extension, which keeps every capture in its own
 * IndexedDB until the web app confirms it was stored, and re-sends until then.
 * Losing the queue therefore costs a re-send, not a capture.
 *
 * Three properties make that safe, and all three are load-bearing:
 *
 * - **Ids come from the client.** A re-send carries the same `id`, so this route
 *   can refuse to queue it twice and the web app can refuse to store it twice.
 *   The server used to mint the id, which made every retry a new capsule.
 * - **Items are addressed to a device.** A poll only drains its own device's
 *   items. Previously any open Capso tab — in any browser, including one opened
 *   by an agent against the same deployment — collected everything.
 * - **Confirmation is explicit.** `ack` promotes an item to `confirmed`, and the
 *   extension drops it only then. If this instance recycles and forgets, the
 *   extension re-sends, the web app dedupes, and it converges.
 */

export type Pending = {
  /** Generated by the extension. Stable across retries — that is the whole point. */
  id: string;
  /** Which browser profile this capture belongs to. Set at pairing time. */
  deviceToken: string;
  imageDataUrl: string;
  source: "extension";
  pageUrl?: string;
  pageTitle?: string;
  /** Host the capture came from — the provenance badge finally has data behind it. */
  sourceApp?: string;
  width?: number;
  height?: number;
  contentHash?: string;
  at: string;
};

const MAX_QUEUED = 20;
/** How long a handed-out capture may go unacknowledged before it is re-offered. */
const IN_FLIGHT_MS = 60_000;
/** Ids remembered as stored. Bounded — this is a cache, and losing it is recoverable. */
const MAX_CONFIRMED = 500;

const queue: Pending[] = [];
/** Handed to a client but not yet confirmed stored. */
const inFlight = new Map<string, { item: Pending; takenAt: number }>();
/** Ids the web app has said it genuinely stored. Insertion-ordered, so eviction is FIFO. */
const confirmed = new Set<string>();

/** Anything a client took but never acknowledged goes back in the queue. */
function reclaim() {
  const now = Date.now();
  for (const [id, entry] of inFlight) {
    if (now - entry.takenAt > IN_FLIGHT_MS) {
      inFlight.delete(id);
      queue.push(entry.item);
    }
  }
}

const known = (id: string) =>
  confirmed.has(id) || inFlight.has(id) || queue.some((q) => q.id === id);

/** Raster only — `data:image/svg+xml` is markup, not a screenshot, and can carry a script. */
const IMAGE_DATA_URL = /^data:image\/(png|jpe?g|webp);base64,/i;
/** Opaque, client-generated, and echoed in URLs and logs — keep it boring. */
const TOKEN = /^[A-Za-z0-9_-]{8,64}$/;

const str = (v: unknown, max = 2048) =>
  typeof v === "string" && v.length <= max ? v : undefined;
const num = (v: unknown) => (typeof v === "number" && Number.isFinite(v) ? v : undefined);

export async function POST(req: Request) {
  let body:
    | (Partial<Pending> & { ack?: string[]; check?: string[] })
    | null;
  try {
    body = await req.json();
  } catch {
    return json({ error: "invalid JSON body" }, 400, req);
  }

  const origin = req.headers.get("origin");
  const sameOrigin = origin === new URL(req.url).origin;
  const fromExtension = Boolean(origin?.startsWith("chrome-extension://"));

  // An acknowledgement, not a capture: the open Capso tab sends this after it has
  // genuinely stored an item, so it must come from this app's own origin — not from
  // the extension (which never acks) and not from any other site.
  if (Array.isArray(body?.ack)) {
    if (!sameOrigin) return json({ error: "forbidden" }, 403, req);
    for (const id of body.ack) {
      if (typeof id !== "string") continue;
      inFlight.delete(id);
      confirmed.add(id);
    }
    // Bounded FIFO. Evicting an id only means the extension re-sends it once more
    // and the web app dedupes — the failure mode is a wasted upload, not a dupe.
    while (confirmed.size > MAX_CONFIRMED) {
      confirmed.delete(confirmed.values().next().value as string);
    }
    return json({ acked: body.ack.length }, 200, req);
  }

  // A delivery check, so the extension can retire an item without re-uploading it.
  // Without this, the only way to learn an item landed is to send the bytes again.
  if (Array.isArray(body?.check)) {
    if (!fromExtension) return json({ error: "forbidden" }, 403, req);
    const ids = body.check.filter((id): id is string => typeof id === "string").slice(0, 100);
    return json({ confirmed: ids.filter((id) => confirmed.has(id)) }, 200, req);
  }

  // CORS blocks a browser from *reading* a cross-origin response, but a `Content-Type:
  // text/plain` body is a CORS "simple request" — no preflight, and the POST still lands.
  // That let any site the user had open write forged captures into their library.
  if (!fromExtension) return json({ error: "forbidden" }, 403, req);

  const id = str(body?.id, 64);
  const deviceToken = str(body?.deviceToken, 64);
  if (!id || !TOKEN.test(id)) return json({ error: "id must be an opaque token" }, 400, req);
  if (!deviceToken || !TOKEN.test(deviceToken)) {
    // Refused rather than defaulted: an unaddressed capture is one that any
    // browser could drain, which is the hazard this field exists to close.
    return json({ error: "deviceToken required — pair the extension first" }, 400, req);
  }

  // `.startsWith` on a non-string (e.g. a bare number in the JSON body) threw and
  // fell through to a bodyless 500 instead of the 400 every other bad input gets.
  if (typeof body?.imageDataUrl !== "string" || !IMAGE_DATA_URL.test(body.imageDataUrl)) {
    return json({ error: "imageDataUrl must be a png/jpeg/webp data URL" }, 400, req);
  }

  // Idempotent. A retry after a lost response, or after this instance recycled
  // and the extension re-sent, must not produce a second capsule.
  if (known(id)) {
    return json({ status: confirmed.has(id) ? "confirmed" : "pending", duplicate: true }, 200, req);
  }

  queue.push({
    id,
    deviceToken,
    imageDataUrl: body.imageDataUrl,
    source: "extension",
    pageUrl: str(body.pageUrl),
    pageTitle: str(body.pageTitle, 512),
    sourceApp: str(body.sourceApp, 128),
    width: num(body.width),
    height: num(body.height),
    contentHash: str(body.contentHash, 128),
    at: new Date().toISOString(),
  });

  // Drop the oldest rather than grow without bound if no app is open to drain.
  // This is no longer data loss — the extension still holds the capture and will
  // re-send it — so 507 is backpressure, and the extension must treat it as
  // "keep and retry" rather than as a failure.
  let dropped = 0;
  while (queue.length > MAX_QUEUED) {
    queue.shift();
    dropped++;
  }

  return json({ status: "pending", queued: queue.length, dropped }, dropped > 0 ? 507 : 200, req);
}

/**
 * Set only by the open Capso tab's own poll. A plain `<img src>` or a
 * cross-site GET carries no Origin header at all, so Origin alone cannot gate
 * this — but only same-origin JS can attach a custom header, and a
 * cross-origin `fetch` that tries to would trigger a preflight that `cors()`
 * below refuses for anything but the extension.
 */
const POLL_HEADER = "x-capso-poll";

/**
 * Hands out pending captures for one device.
 *
 * Items are held in flight rather than deleted: `splice` used to remove them at
 * read time, so if the client threw while storing item 2 of 5 — or the tab
 * closed mid-loop — items 3 to 5 were gone from both sides with nothing
 * reporting it.
 *
 * The `device` filter is what stops a second Capso tab, in a second browser,
 * from silently collecting captures meant for the first.
 */
export async function GET(req: Request) {
  if (req.headers.get(POLL_HEADER) !== "1") {
    return json({ error: "forbidden" }, 403, req);
  }
  const device = new URL(req.url).searchParams.get("device");
  if (!device || !TOKEN.test(device)) {
    return json({ error: "device required" }, 400, req);
  }

  reclaim();
  const mine = queue.filter((q) => q.deviceToken === device);
  for (let i = queue.length - 1; i >= 0; i--) {
    if (queue[i]!.deviceToken === device) queue.splice(i, 1);
  }
  const now = Date.now();
  for (const item of mine) inFlight.set(item.id, { item, takenAt: now });
  return json({ items: mine });
}

export async function OPTIONS(req: Request) {
  return new Response(null, { status: 204, headers: cors(req) });
}

/**
 * Only a Capso extension may talk to this endpoint, and only to POST.
 *
 * This used to return `access-control-allow-origin: *` on every response —
 * including the GET that drains the queue — which meant any page the user
 * happened to visit could read the full base64 of screenshots taken from their
 * private tabs, and push forged captures into their library.
 */
function cors(req: Request): Record<string, string> {
  const origin = req.headers.get("origin");
  if (!origin?.startsWith("chrome-extension://")) return {};
  return {
    "access-control-allow-origin": origin,
    "access-control-allow-headers": "content-type",
    "access-control-allow-methods": "POST, OPTIONS",
    vary: "origin",
  };
}

function json(body: unknown, status = 200, req?: Request) {
  return NextResponse.json(body, { status, headers: req ? cors(req) : {} });
}
